### ISSUE TITLE
Super Duper mode "space to select" is not working with "h" key

### ISSUE THREAD

**Issue by garrofederico** [brandonkboswell/keyboard#1]
When I'm pressing (s)+(d) and holding (space) to select text, it only works when moving forward (pressing (l) key) and not when moving backwards (pressing (h). So that means I cannot select the text that is before the cursor.

So to sum up, the key combination (s)+(d)+(space)+(h) is not working for me

**Comment by brandonkboswell** [comment]
Hey @garrofederico, I've also noticed the same thing, but I think it is app specific. For instance, I notice that it doesn't work in Notion, but it does work in Sublime Text. 

Are you noticing this all of the time or only in specific apps?

Either way it's useful to know that someone else is experiencing this as well and that I'm not going crazy. ;)

**Comment by garrofederico** [comment]
Hi @brandonkboswell ! First of all, many thank for all this development!! I have been using it for a while now and I'm super happy with it :). 

Regarding the issue, I have it on all apps, and after investigating the issue a bit with Karabiner-EventViewer, it's the output of Karabiner that is not triggered when hitting this combination of keys, not an app that is not accepting it (at least in my case).

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/68641690/183438252-bc0b9095-e20d-425f-9478-1b492d328947.png">

it is only doing something if I hit [(s)+(d)+(space)+(l)] and not when  hitting [(s)+(d)+(space)+(h)].

Can it be an issue related with keybiding shorcuts on Karabiner's json?

**Comment by brandonkboswell** [comment]
Hmm... I would say check your karabiner JSON and also make sure there's not any other apps that could be intercepting this. I did have issues with Better Touch Tool conflicting with Karabiner awhile back and uninstalled it. When I check my event viewer, I get proper left and right arrows with the left shift modifier.

**Comment by brandonkboswell** [comment]
@garrofederico, this appears to be the issue I was experiencing. I run into this issue with the internal keyboard on M1 MacBook Pro, but my Massdrop Alt handles it just fine. Oddly, It occurs with the H key, but not with j,k, or l keys.

**Comment by garrofederico** [comment]
@brandonkboswell 
Indeed, this is the issue that I'm having too. I'm using a 2018 Macbook pro with Touchbar and is not working, but when I use an external keyboard, I don't have the ghosting issue any more.

Many thanks for your your help!
